### ISSUE TITLE
ReadMe does not list Dependencies 

### ISSUE THREAD

**Issue by itsSaad** [ruby-av/paperclip-av-transcoder#10]
Can we please have a list of dependencies this gem depends on. like ffmpeg

I get this error on uploading video.

    LoadError (cannot load such file --/Users/SM/Developer/QBXNet/RoR/etracs/project/lib/paperclip_processors/transcoder.rb)

any other files needed. where do we get this file?

**Comment by owahab** [comment]
The dependencies should not be listed in the README file, the gemspec is usually the expected location since Ruby Gem will automatically pull required dependencies.
I haven't came across this error before and I need a lot more information. Can you post the full error stack?

**Comment by owahab** [comment]
Closing for being inactive.

**Comment by shokunin-kishitsu** [comment]
Same problem.
```
cannot load such file -- /releases/20150527180521/lib/paperclip_processors/transcoder.rb
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/processor.rb:64:in `load_processor'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/processor.rb:56:in `processor'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:523:in `block in post_process_style'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:522:in `each'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:522:in `inject'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:522:in `post_process_style'
/home/web/camdolls/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:515:in `block in post_process_styles'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:514:in `each'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:514:in `post_process_styles'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:506:in `block (2 levels) in post_process'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:458:in `_run__413283399654332819__attachment_post_process__3167645885543296521__callbacks'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_attachment_post_process_callbacks'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/callbacks.rb:36:in `run_paperclip_callbacks'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:504:in `block in post_process'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:403:in `_run__413283399654332819__post_process__3167645885543296521__callbacks'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_post_process_callbacks'
/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/callbacks.rb:36:in `run_paperclip_callbacks'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:503:in `post_process'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:459:in `post_process_file'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:107:in `assign'
/shared/bundle/ruby/2.1.0/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:334:in `reprocess!'
```

**Comment by owahab** [comment]
Are you sure you did run `bundle install` after adding the gem to your Gemfile?

**Comment by shokunin-kishitsu** [comment]
paperclip-av-transcoder is in Gemfile.lock

**Comment by owahab** [comment]
@shokunin-kishitsu can you try Paperclip < 4.2 and let me know the result?

**Comment by shokunin-kishitsu** [comment]
I ended up registering a custom processor in initializer and not using the gem.

**Comment by shokunin-kishitsu** [comment]
Do I need to require some files or it should work out of the box?

**Comment by itsSaad** [comment]
Yes. I solved this by downgrading the gem itself. an earlier version worked for me.

**Comment by shokunin-kishitsu** [comment]
Here's how I made it work.  In /initializers/paperclip_processors.rb:

```
require 'paperclip/av/transcoder'

Paperclip.configure do |c|
  c.register_processor :transcoder, Paperclip::Transcoder
end
```

**Comment by owahab** [comment]
@shokunin-kishitsu awesome. Will give that a try.

**Comment by tedma4** [comment]
@itsSaad What versions of av-transcoder and paperclip did you use to get this to work?

**Comment by davidpatters0n** [comment]
@tedma4 I took the slightly different approach and successfully now have this working. (tears of joy) :bowtie: I upgraded paperclip to 4.3.0 which just got released 9 days ago. Let me know how this works for you and hopefully helps others

**Comment by RailsCod3rFuture** [comment]
I'm on Windows 10, and it doesn't work for me. I'm unable to see video posts, and it rolls back automatically once the encoding process succeeds.
