### ISSUE TITLE
Av::CommandError for 0.6.4

### ISSUE THREAD

**Issue by itsSaad** [ruby-av/paperclip-av-transcoder#16]
Im still having this issue although it was fixed with this release.

    Av::CommandError (error while running command if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi: Command 'PATH=/usr/bin/:$PATH if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi' returned 1. Expected 0
    DEBUG [6a1eae9e] 	Here is the command output:
    DEBUG [6a1eae9e] 	
    DEBUG [6a1eae9e] 	):
    DEBUG [6a1eae9e] 	  app/controllers/blog_posts_controller.rb:37:in `create'

**Comment by itsSaad** [comment]
https://github.com/ruby-av/paperclip-av-transcoder/issues/8

**Comment by tedma4** [comment]
I'm having the same problem

[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi-v was unexpected at this time.
   (1.0ms)  rollback transaction
Completed 500 Internal Server Error in 7974ms

Av::CommandError (error while running command if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi: Command 'if command -v avprobe 2>/dev/null; then echo "true"; else cho "false"; fi' returned 1. Expected 0
Here is the command output:

):
  app/controllers/shouts_controller.rb:32:in `create'

model.rb
    has_attached_file :snip,  
                      styles: {
                              medium: { :geometry => "640x480#", :format => 'mp4', streaming: true },
                               thumb: { :geometry => "100x100#", :format => 'jpg', time: 10 },
                           }, :processors => [:transcoder]

**Comment by tedma4** [comment]
If i remove :processors => [:transcoder] the video uploads and a screenshot is shown but the video doesn't play.

**Comment by owahab** [comment]
Are you running paperclip 4.2+? There seems to be an issue with `paperclip-av-transcoder` 0.6.4 and `paperclip` 4.2+
See https://github.com/ruby-av/paperclip-av-transcoder/issues/10#issuecomment-106248787

**Comment by tedma4** [comment]
I was using av-transcoder 0.6.3 and paperclip 4.2.1, but even after updating to av-transcoder 0.6.4 and trying paperclip 4.2.2 and going as far back as 4.0.0, I the same thing [here](http://pastie.org/private/otudoqwv1fw1nzbsznrgkw) and [here](http://pastie.org/private/ydzml2w5avnqmqnp8uuag). From the paperclip [NEWS](https://github.com/thoughtbot/paperclip/blob/master/NEWS) file, it says they updated the custom processors in lib/paperclip, but using processors: [:transcoder] doesn't work for me. 

I replaced :transcoder with :ffmpeg and got this [error](http://pastie.org/private/b8xy23lorgv6e70nlz3vvq) using paperclip 4.2.2 and this [error](http://pastie.org/private/uw5wkremvytdxq5acb5xmq) with paperclip 4.1.1

**Comment by 8CciaN8** [comment]
+1 got the same error when using transcoder as paperclip processor.

Hope you could help me, thanks :)

**Comment by DaGraves** [comment]
I am getting this same error. Has anyone come up with a fix for this?

**Comment by RailsCod3rFuture** [comment]
+1 Same. I'm receiving the error when I upload videos. Neither Paperclip nor Carrier Wave Video are allowing me to upload and show video files.

**Comment by seyna** [comment]
For those who tried a lot of times but in vain.

After hours of trying, It strikes me that maybe the error lies in choosing `avconv`
```
[AV] Found ["avconv", "ffmpeg"], using: avconv
```

If you use Ubuntu like me, you might at first install `ffmpeg` using ppa and because of dependency install `avconv` as well. Unfortunately it seems that `avconv` not function correctly.

Finally I decide to remove `ffmpeg`, `avconv` packages and reinstall `ffmpeg` static build.

```
> sudo apt-get remove ffmpeg  
> sudo apt-get purge libav-tools
```

`ffmpeg` static build here => http://johnvansickle.com/ffmpeg/

```
> wget http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
> tar xf ffmpeg-git-64bit-static.tar.xz
> sudo mv ff* qt-faststart /usr/bin/
```

These steps work for me. Hope it works for you too.
